# Generated by Django 2.2.5 on 2019-09-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'Flex Page', 'verbose_name_plural': 'Flex Pages'},
        ),
        migrations.AlterField(
            model_name='flexpage',
            name='newsubtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
