# Generated by Django 2.2.5 on 2019-09-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Email in here', max_length=100)),
                ('full_name', models.CharField(help_text='full name here', max_length=100)),
            ],
        ),
    ]
